Repository equinor/cc-components, pull requests merged in 2023-08, with the labels that each got.

#444 fix/workorder status color
  libs/workorderapp/src/lib/types/extendedGardenFields.ts
  libs/workorderapp/src/lib/types/index.ts
  libs/workorderapp/src/lib/ui-garden/Item.tsx
  libs/workorderapp/src/lib/utils-garden/columnKeyAccessor.ts
  libs/workorderapp/src/lib/utils-garden/getGroupBy.ts
  libs/workorderapp/src/lib/utils-garden/getHighlightedColumn.ts
  libs/workorderapp/src/lib/utils-garden/getWorkOrderStatuses.ts
  libs/workorderapp/src/lib/utils-garden/index.ts
  libs/workorderapp/src/lib/utils-garden/sortPackages.ts
  libs/workorderapp/src/lib/utils-statuses/followup/getFollowUpStatus.ts
  libs/workorderapp/src/lib/utils-statuses/getColorBasedOnGroupBy.ts
  libs/workorderapp/src/lib/utils-statuses/getStatusFn.ts
  libs/workordershared/src/lib/types/workorder.ts
Labels: bug, data

#459 build: test action
  .github/workflows/pr-deploy.yml
  apps/handover/package.json
  apps/workorder/package.json
  apps/workorder/src/main.tsx
  cli/package.json
  cli/src/commands/releasePr.ts
  github-action/package.json
  github-action/src/parsePackageJson.ts
  github-action/src/releasePr.ts
  github-action/tsconfig.json
  libs/handoverapp/src/lib/config/frameworkConfig.ts
  libs/handoverapp/src/lib/config/gardenConfig.ts
  libs/handoversidesheet/package.json
  libs/handoversidesheet/src/lib/ui-sidesheet/sidesheet.styles.ts
  libs/loopsidesheet/package.json
  libs/loopsidesheet/src/lib/ui-sidesheet/LoopSidesheet.tsx
  libs/mechanicalcompletionsidesheet/package.json
  libs/punchsidesheet/package.json
  libs/punchsidesheet/src/lib/ui-sidesheet/sidesheet.styles.ts
  libs/shared/src/packages/fusion-framework/createRender.tsx
  libs/swcrsidesheet/package.json
  libs/workordersidesheet/package.json
  libs/workordersidesheet/src/lib/ui-sidesheet/WorkorderSidesheet.tsx
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo.json
Labels: QA Required

#469 ci: add approve check to pr deployment
  .github/workflows/pr-deploy.yml
Labels: QA Required

#470 ci: test check
  .github/workflows/pr-deploy.yml
Labels: QA Required

#471 fix: :bug: fix pr label unrender
  .github/workflows/pr-deploy.yml
  libs/shared/src/packages/fusion-framework/createRender.tsx
Labels: QA Required

#475 fix: :bug: Fix all material status displayed as "Not Availible". Fix …
  apps/workorder/src/main.tsx
  libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/material/AvailableItemCell.tsx
  libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/material/columns.tsx
  package.json
Labels: QA Required

#483 feat::sparkles: bump workspace v4
  .github/workflows/pr-deploy.yml
  libs/handoverapp/package.json
  libs/loopapp/package.json
  libs/mechanicalcompletionapp/package.json
  libs/powerbiapp/package.json
  libs/powerbiapp/src/Report.tsx
  libs/punchapp/package.json
  libs/scopechangerequestapp/package.json
  libs/shared/package.json
  libs/shared/src/packages/workspace-config/src/useGardenDataSource.ts
  libs/swcrapp/package.json
  libs/workorderapp/package.json
  package.json
  pnpm-lock.yaml
Labels: QA/UAT

#500 fix(workspace): garden popover not closing on outside click
  libs/shared/src/packages/workspace-config/src/useGardenDataSource.ts
  package.json
  pnpm-lock.yaml
Labels: bug
